name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Installer dépendances
        run: npm install

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Compiler APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: shapshop-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
